#!/usr/bin/env bash

# fail on first error
set -euo pipefail

# make sure the domain argument is present
if [ $# -ne 1 ]; then
    echo >&2 "usage: phpenv-detect-current-version domain"
    exit 1;
elif [[ "$1" =~ [^0-9a-zA-Z_-] ]]; then
    echo "Domain may only contain alphanumerical characters (and the '_' and '-' characters)";
    exit 1;
fi

# the domain to check
DOMAIN=${1,,}

# detect path to current configuration file
PATH=$(ls /etc/php/*/fpm/pool.d/www-${DOMAIN}.conf)

# extract PHP version from path
# PHP_VERSION=$(echo "${PATH}" | cut -d'/' -f 4)
PHP_VERSION=${PATH:9:3}

echo "${PHP_VERSION}"
