#!/usr/bin/env bash

# fail on first error
set -euo pipefail

# detect required PHP version
PHP_VERSION=$(/opt/bin/phpenv/phpenv-php-required-version)

# PHP executable
PHP="/usr/bin/php${PHP_VERSION}"

# if PHP executable is not really executable, fail hard
if ! [ -x "$(command -v ${PHP})" ]; then
    echo >&2 "Error: PHP executable not found or not executable (${PHP})"
    exit 1;
fi

# start PHP executable with all arguments passed to this script
"${PHP}" "$@"
